### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by Deftknot** [igorkulman/ChangeMenuBarColor#11]
When I run the executable version it finishes the task and thats it:

OVERVIEW: A Swift command-line tool to create a custom menu bar color wallpaper
for macOS Big Sur

USAGE: ChangeMenuBarColor <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  SolidColor              Adds solid color rectangle
  Gradient                Adds gradient rectangle

  See 'ChangeMenuBarColor help <subcommand>' for detailed help.
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process finished]

Am I doing something wrong?

**Comment by igorkulman** [comment]
Check out the Readme, you are suppose to provide it with parameters so it knows what to generate.
