### ISSUE TITLE
generated image resized incorrectly

### ISSUE THREAD

**Issue by seventhaxis** [igorkulman/ChangeMenuBarColor#15]
I'm using a static version of one of the Big Sur dynamic images. When I run the program it does a great job of adding the appropriate solid color for my menu bar, but it has badly distorted the image.

<img width="1680" alt="Screen Shot 2020-12-03 at 10 31 54 AM" src="https://user-images.githubusercontent.com/4438390/101050813-c5f9b980-3552-11eb-84de-33359ca348e9.png">

Here is the original static background image:

![bigsur_8](https://user-images.githubusercontent.com/4438390/101051147-2688f680-3553-11eb-9aad-84a75322b580.jpg)

**Comment by igorkulman** [comment]
You are right the tool just resizes the images without keeping it ratio if it is different. This needs to be fixed.

**Comment by igorkulman** [comment]
Should be fixed now, I tested it with a few ultra wide wallpapers
