### ISSUE TITLE
Can I have your wallpaper?!!

### ISSUE THREAD

**Issue by hezhii** [igorkulman/ChangeMenuBarColor#18]

**Comment by igorkulman** [comment]
I got it from https://www.wallpaperflare.com/silhouette-of-mountain-simple-simple-background-minimalism-wallpaper-phxwd

**Comment by thamaraiselvam** [comment]
Gradient colors 
```./ChangeMenuBarColor Gradient "#c2001d" "#2600c1" ~/Downloads/wallpaperflare.com_wallpaper.jpg```
