### ISSUE TITLE
Generate image goes under actual menu bar 

### ISSUE THREAD

**Issue by thamaraiselvam** [igorkulman/ChangeMenuBarColor#20]
I have generated image but it is not visible

```
⚡️99% at 09:39:31 PM ❯ ./ChangeMenuBarColor Gradient "#FF0000" "#00FF00" ~/Downloads/wallpaperflare.com_wallpaper.jpg
Starting up
Found 1 screens

Processing screen 1 of 1
Loaded /Users/thamaraiselvam/Downloads/wallpaperflare.com_wallpaper.jpg to be used as wallpaper image
Generating gradient image
Created new wallpaper for screen 1 in file:///Users/thamaraiselvam/Library/Application%20Support/ChangeMenuBarColor//wallpaper-screen1-adjusted-76224A37-A6C1-45FC-AAE5-1E89B179BFE5.jpg
Wallpaper set


All done!
```
Not visible after script executed

<img width="1440" alt="Screenshot 2020-12-09 at 9 44 50 PM" src="https://user-images.githubusercontent.com/6559664/101655577-c66ce580-3a67-11eb-837c-35c2d11e5512.png">

But If I hide menu then it is visible.
<img width="1436" alt="Screenshot 2020-12-09 at 9 45 12 PM" src="https://user-images.githubusercontent.com/6559664/101655635-d5539800-3a67-11eb-8032-9c8e9d946245.png">

**Comment by igorkulman** [comment]
Looks like the generated image is correct. Did you disable transparency in macOS?

**Comment by thamaraiselvam** [comment]
Fixed it by unchecking `Accessibility>Display>Reduce Transparency`
