### ISSUE TITLE
Add functionality to run command on multiple files.

### ISSUE THREAD

**Issue by Chett23** [igorkulman/ChangeMenuBarColor#23]
would it be possible to run the command and provide a path to a directory filled with multiple files and run the command on all of the files?

I have a directory of 80+ wallpapers and dont want to have to run the command for each one.

**Comment by igorkulman** [comment]
This is not exactly a use case I had in mind. The idea is that if you want to change the wallpaper you use the utility.

**Comment by Chett23** [comment]
Would it be possible to add the functionality but instead of setting the new file as wallpaper it save the new wallpaper to a new/specified dir and then you can save the wallpaper for later? I really like the ability to choose the status bar color especially with how many wallpapers I use, and I'm sure many others too. Or even just add the functionality to save the new wallpaper to a specified for because I can easily run a for loop in terminal but currently You don't have the option to save so if I run a loop it just changes my wallpaper until it gets to the last one. I think adding the ability to save the new file would add to the use cases of this.

**Comment by igorkulman** [comment]
The utility did just that before 0.4.0, so you can try downloading 0.3.1 and use it, the syntax was a bit different though. Or you can run the current version and then go to `~/Library/Application Data/ChangeMenuBarColor` where you will find the generated files.
