### ISSUE TITLE
New wallpaper with solid color menu bar is severely reduced in quality

### ISSUE THREAD

**Issue by EminFPS** [igorkulman/ChangeMenuBarColor#24]
My original file is a few megabytes, while the new file ends up being under 500 kilobytes or even less. This happens every time.

**Comment by igorkulman** [comment]
Probably needs some export tweak, like setting image quality or compression.

**Comment by igorkulman** [comment]
I disabled JPEG compression, for me the new generated file is now twice the size of the generated file before this change.

**Comment by igorkulman** [comment]
Also #33 should help.
