### ISSUE TITLE
Support -s parameter for silent execution

### ISSUE THREAD

**Issue by powermic** [igorkulman/ChangeMenuBarColor#26]
Hi, it would be great to have a small tweak in running the command ./ChangeMenuBarColor with optional -s parameter to run it silently.

**Comment by igorkulman** [comment]
What exactly do you mean by running silently?

**Comment by powermic** [comment]
I may run it with > /dev/null/ but would like to be able to run with a flag like -s (commonly used flag) and don't see any echo messages like:

```
Starting up
Using currently set macOS wallpaper file:///Users/powermic/Library/Application%20Support/ChangeMenuBarColor//wallpaper-screen-adjusted-DFCFFF76-A0F7-46D3-882A-7017A130BF8A.jpg
Generating solid color image
Created new wallpaper for the main screen in file:///Users/powermic/Library/Application%20Support/ChangeMenuBarColor//wallpaper-screen-adjusted-F60C5F2E-DFC7-4588-A27F-C70A7D201810.jpg
Wallpaper set
All done!
```

**Comment by igorkulman** [comment]
Sorry, I do not see a point in this. Just do `>/dev/null 2>&1` if you do not like the output.
