### ISSUE TITLE
Exception not handled when SolidColor argument is not wrapped in quotes

### ISSUE THREAD

**Issue by orchetect** [igorkulman/ChangeMenuBarColor#29]
When you run the tool in Terminal and forget that the `SolidColor` argument requires double-quotes, there is no helpful error message. Instead, a segmentation fault or other unhandled exception gets dumped to the console.

This threw me (no pun intended), and I thought the file was not being seen as executable by Terminal or there were some security/permissions issues so I went on a wild goose chase for a while before realizing what the actual problem was.

```
$ ./ChangeMenuBarColor SolidColor #000000
Segmentation fault: 11

$ ./ChangeMenuBarColor SolidColor #000000
ChangeMenuBarColor(74179,0x1115e4e00) malloc: Incorrect checksum for freed object 0x7fcb7ad0d3c8: probably modified after being freed.
Corrupt value: 0x4ffffffe00000000
ChangeMenuBarColor(74179,0x1115e4e00) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

It may make more sense to catch this and have an error printed out expected regarding argument format. Or just print out the default command description (root level man page that shows when you just run `./ChangeMenuBarColor `)

Or figure out a way with the argument parser to accept it without needing the double-quotes?

**Comment by igorkulman** [comment]
I think this is a shell problem. The "#" generally means start of a comment.

If I just do `print(CommandLine.arguments)` in the utility and execute 

`swift run ChangeMenuBarColor #000`

 I get 

`[".build/x86_64-apple-macosx/debug/ChangeMenuBarColor"]` 

meaning the `#000` never got passed to the utility from the shell, the shell ignored it as a comment.
