### ISSUE TITLE
Change Menu Bar Color for multiple displays

### ISSUE THREAD

**Issue by hayesref** [igorkulman/ChangeMenuBarColor#32]
Any ideas to make sure the Menu Bar color is changed on all displays? Currently only changes the Menu Bar located on the Mac itself. If not, how may I set the menu bar color back to its default? Thank you in advance.

**Comment by igorkulman** [comment]
At the beginning the tool set wallpapers for all displays. Then there was a complaint that the menu bar is only visible on the main display so only the main display wallpaper should be set.

**Comment by joshuaar12** [comment]
I have the menu bar on all of my displays - so it's necessary to change the color on all the menu bars for me. Is there a way to download old directory that changes all the display menu bars?

**Comment by igorkulman** [comment]
> I have the menu bar on all of my displays - so it's necessary to change the color on all the menu bars for me. Is there a way to download old directory that changes all the display menu bars?

As a workaround your can run the utility, set the second display as main, run it again amd then set your main display back.

And I need to somehow find a way to detect if the menu bar is shown on all display or just the primary one.

**Comment by hayesref** [comment]
Negative. When I set the second display as main, the changed Menu Bar moves with it. I ran the utility again just to see, it moved again when I changed the main display. Still 1 changed, 2 unchanged

Eric Hayes
C - 580-336-8640
hayesref@gmail.com

**Comment by igorkulman** [comment]
I will add a parameter to set all displays when I have some time.

**Comment by barjon** [comment]
same issue

**Comment by igorkulman** [comment]
I add the option in #38. Download the latest code and `--all-displays` flag at the end of the command, so for example `./ChangeMenuBarColor Gradient "#FF0000" "#00FF00" --all-displays`.

**Comment by barjon** [comment]
@igorkulman Missing release?

**Comment by igorkulman** [comment]
> @igorkulman Missing release?

Added as 0.8.0.
