### ISSUE TITLE
Changing color only works with terminal not in full screen

### ISSUE THREAD

**Issue by kedarabhyankar** [igorkulman/ChangeMenuBarColor#34]
If terminal is in full screen, the app will only change the menu bar color for terminal. If you swipe to any other app, the menu bar is still the old color (in my case, the solid color before I shifted to a gradient color). In order for the color to work, the command has to be re-run when terminal is not full screened. Thanks for such a great app!

**Comment by igorkulman** [comment]
I do not really get it, could your post some scre screenshot or video?

**Comment by kedarabhyankar** [comment]
Yup, sure! Here:


https://user-images.githubusercontent.com/11903995/104350649-65a35380-54d2-11eb-9be3-6cfa43e7b754.mp4

Hopefully this illustrates what's going on.

**Comment by igorkulman** [comment]
I think this is a duplicate of #17 as a full screen app creates a virtual desktop.

**Comment by kedarabhyankar** [comment]
Gotcha. Thanks!
