### ISSUE TITLE
Error when setting SolidColor on all displays

### ISSUE THREAD

**Issue by HAL9000-cmd** [igorkulman/ChangeMenuBarColor#39]
Hi,

I've got a triple monitor setup. It does implement the SolidColor on my main display normally, but fails to do so on my other 2 displays, throwing the following error in the terminal when using the command with `--all-displays`:
```
Could not create graphical context for solid color image
Could not generate new wallpaper screen 1
```
```
Could not create graphical context for solid color image
Could not generate new wallpaper screen 2
```

**Comment by igorkulman** [comment]
Any chance you use dynamic wallpapers?

**Comment by HAL9000-cmd** [comment]
Nope. Double checked to make sure that's not the case on all displays. I've got my MacBook Pro lid closed with those 3 screens connected to it. Made sure that no dynamic wallpaper is used either on my MacBook Pro even though it's always closed.

**Comment by wattachai** [comment]
I'm running into the same issue. Note that, it applies to `Gradient` option as well.

**Comment by igorkulman** [comment]
Try explicitly specifying a wallpaper path as a parameter.

**Comment by wattachai** [comment]
> Try explicitly specifying a wallpaper path as a parameter.

no luck 😞

**Comment by igorkulman** [comment]
To be honest I do not know what the problem is, seems to be specific to your machines or displays. I just know it is related to https://github.com/igorkulman/ChangeMenuBarColor/blob/main/Sources/ChangeMenuBarColor/Extensions/ImageFunctions.swift#L67 and only way to move forward I can think of is trying different parameters on your machines and seeing which one helps.

**Comment by goedtkindt** [comment]
same here, just installed Big Sur over Catalina, and:
-screen-adjusted-43923282-D51D-461A-BABF-54AD26B4CBE6.jpg
Wallpaper set
Using currently set macOS wallpaper file:///System/Library/CoreServices/DefaultDesktop.heic
Generating black solid color image
Could not create graphical context for solid color image
Could not generate new wallpaper screen 1
Using currently set macOS wallpaper file:///System/Library/CoreServices/DefaultDesktop.heic
Generating black solid color image
Could not create graphical context for solid color image
Could not generate new wallpaper screen 2

All done!

MacBook Pro with 2 external monitors - those monitors set to fixed wall paper.  Happy to help.

**Comment by Hok-dev** [comment]
I got 
`Could not generate new wallpaper screen 0`
with one display

**Comment by wwhtrbbtt** [comment]
I have the same problem. I really like the project though!

**Comment by david34corbalan** [comment]
the problem is found when the menu is shown automatically, then (screen.menuBarHeight = 0.0), both in SolidColor (line 47) and Gradient (line 56) this generates an error, I am a programmer in other languages, I would like to be able to help you more in this problem.

**Comment by prebm** [comment]
@igorkulman I was able to start a debug session in XCode and narrow down the problem to [NSScreen#menuBarHeight](https://github.com/igorkulman/ChangeMenuBarColor/blob/main/Sources/ChangeMenuBarColor/Extensions/NSScreen%2BExtensions.swift#L17). I am by no means a swift developer but I hope the following output will help to fix the problem. Please feel free to contact me if I can help with more debug output.

```bash
# Main Screen (4K Monitor)

frameSizeHeight	CGFloat	1440	
visibleFrameHeight	CGFloat	1415	
visibleFrameOriginY	CGFloat	0	
bakcingScaleF	CGFloat	2	
returns	CGFloat	50	

# Second Screen (Retina MacBookPro 13")

frameSizeHeight	CGFloat	900	
visibleFrameHeight	CGFloat	900	
visibleFrameOriginY	CGFloat	260	
bakcingScaleF	CGFloat	2	
returns	CGFloat	-520	

# Third Screen (1920 x 1200)

frameSizeHeight	CGFloat	1200	
visibleFrameHeight	CGFloat	1200	
visibleFrameOriginY	CGFloat	240	
bakcingScaleF	CGFloat	1	
returns	CGFloat	-240	

```

#### Command

`./ChangeMenuBarColor SolidColor "#d0deec" "/Users/path/to/my.jpg" --all-displays`

Main Screen is working, second and third are giving the above mentioned errors.

#### Side note

I've changed the return of the [NSScreen#menuBarHeight](https://github.com/igorkulman/ChangeMenuBarColor/blob/main/Sources/ChangeMenuBarColor/Extensions/NSScreen%2BExtensions.swift#L16) to the following which works perfectly in my setting.

```swift
return 25 * backingScaleFactor
```

**Comment by igorkulman** [comment]
> @igorkulman I was able to start a debug session in XCode and narrow down the problem to [NSScreen#menuBarHeight](https://github.com/igorkulman/ChangeMenuBarColor/blob/main/Sources/ChangeMenuBarColor/Extensions/NSScreen%2BExtensions.swift#L17). I am by no means a swift developer but I hope the following output will help to fix the problem. Please feel free to contact me if I can help with more debug output.
> 
> ```shell
> # Main Screen (4K Monitor)
> 
> frameSizeHeight	CGFloat	1440	
> visibleFrameHeight	CGFloat	1415	
> visibleFrameOriginY	CGFloat	0	
> bakcingScaleF	CGFloat	2	
> returns	CGFloat	50	
> 
> # Second Screen (Retina MacBookPro 13")
> 
> frameSizeHeight	CGFloat	900	
> visibleFrameHeight	CGFloat	900	
> visibleFrameOriginY	CGFloat	260	
> bakcingScaleF	CGFloat	2	
> returns	CGFloat	-520	
> 
> # Third Screen (1920 x 1200)
> 
> frameSizeHeight	CGFloat	1200	
> visibleFrameHeight	CGFloat	1200	
> visibleFrameOriginY	CGFloat	240	
> bakcingScaleF	CGFloat	1	
> returns	CGFloat	-240	
> ```
> 
> #### Command
> 
> `./ChangeMenuBarColor SolidColor "#d0deec" "/Users/path/to/my.jpg" --all-displays`
> 
> Main Screen is working, second and third are giving the above mentioned errors.
> #### Side note
> 
> I've changed the return of the [NSScreen#menuBarHeight](https://github.com/igorkulman/ChangeMenuBarColor/blob/main/Sources/ChangeMenuBarColor/Extensions/NSScreen%2BExtensions.swift#L16) to the following which works perfectly in my setting.
> 
> ```swift
> return 25 * backingScaleFactor
> ```

Thanks a lot @prebm this helps! Could you try something for me? Change https://github.com/igorkulman/ChangeMenuBarColor/blob/main/Sources/ChangeMenuBarColor/Extensions/NSScreen%2BExtensions.swift#L17 to

```swift
var menuBarHeight: CGFloat {
    return frame.height - visibleFrame.height - (visibleFrame.origin.y - frame.origin.y) - 1
}
```
and  tells me if it helps.

If not then as a hack I can use your `25 * backingScaleFactor` if the computed size is negative.

**Comment by prebm** [comment]
> 
> Thanks a lot @prebm this helps! Could you try something for me? Change https://github.com/igorkulman/ChangeMenuBarColor/blob/main/Sources/ChangeMenuBarColor/Extensions/NSScreen%2BExtensions.swift#L17 to
> 
> ```swift
> var menuBarHeight: CGFloat {
>     return frame.height - visibleFrame.height - (visibleFrame.origin.y - frame.origin.y) - 1
> }
> ```
> 
> and tells me if it helps.
> 
> If not then as a hack I can use your `25 * backingScaleFactor` if the computed size is negative.

@igorkulman, glad to help. Unfortunately, your changes do not work, see the results for reference below. 

```bash
# Main Screen (4K Monitor)

frameSizeHeight	CGFloat	1440	
frameHeight	CGFloat	1440	
visibleFrameHeight	CGFloat	1415	
visibleFrameOriginY	CGFloat	0	
frameOriginY	CGFloat	0	
bakcingScaleF	CGFloat	2	
result	CGFloat	24	

# Second Screen (Retina MacBookPro 13")

frameSizeHeight	CGFloat	900	
frameHeight	CGFloat	900	
visibleFrameHeight	CGFloat	900	
visibleFrameOriginY	CGFloat	260	
frameOriginY	CGFloat	260	
bakcingScaleF	CGFloat	2	
result	CGFloat	-1	

# Third Screen (1920 x 1200)

frameSizeHeight	CGFloat	1200	
frameHeight	CGFloat	1200	
visibleFrameHeight	CGFloat	1200	
visibleFrameOriginY	CGFloat	240	
frameOriginY	CGFloat	240	
bakcingScaleF	CGFloat	1	
result	CGFloat	-1	

```

**Comment by igorkulman** [comment]
Ok everyone, I pushed code changes with fallback to the height computed by @prebm. Let me know of it also works for you.
