### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jetpants** [igorkulman/ChangeMenuBarColor#40]
I cloned the latest version and followed the instructions.

I'm getting compile errors, starting with:

`/Users/steve/Desktop/ChangeMenuBarColor: error: manifest parse error(s):
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
#include <CoreFoundation/CFBase.h>
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:73:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:73:
#include <Block.h>`

**Comment by igorkulman** [comment]
Make sure your are on Big Sur and have the latest XCode 12.3 installed

**Comment by jetpants** [comment]
I'm on both

**Comment by igorkulman** [comment]
Using the pre-built binary or building yourself?

**Comment by jetpants** [comment]
I had a run-time error with the pre-built so I downloaded the sources.

I just did this:

installed Xcode
git clone https://github.com/igorkulman/ChangeMenuBarColor.git
cd ChangeMenuBarColor
swift build -c release

**Comment by igorkulman** [comment]
Then I would say something is wrong with your Xcode.

**Comment by jetpants** [comment]
It's a fresh install this morning. Starts up okay, looks good.

**Comment by igorkulman** [comment]
No idea what my be wrong, you can try opening the project in Xcode and building or running it there as last try.

**Comment by jetpants** [comment]
Great idea. What's the extension on the project file. I couldn't see what
to open as a project.

**Comment by igorkulman** [comment]
It is a Swift Package Manager project, so just open the folder in Xcode and it will work.

**Comment by jetpants** [comment]
I did a clean and a build in Xcode, all good. When I run it at the command
line it looks like it's still building something:

~/Desktop/ChangeMenuBarColor> swift run ChangeMenuBarColor
"../crisp-blue-sky-coast-pxhere.com-2560x1600.jpg" "#8194C1"
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:10:
note: in file included from
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
#include <CoreFoundation/CFBase.h>
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:73:10:
note: in file included from
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:73:
#include <Block.h>

**Comment by igorkulman** [comment]
What does `xcode-select -p` print? 

You can run it via Xcode as a workaround, there is way to define parameters in Xcode.

**Comment by jetpants** [comment]
It prints: /Applications/Xcode.app/Contents/Developer

That works, I'm running it from within Xcode.

Thanks for your help :)
