### ISSUE TITLE
Receiving an error on Catalina

### ISSUE THREAD

**Issue by ArrowNemesis** [igorkulman/ChangeMenuBarColor#42]
When I execute "swift build -c release" it receive this:
error: terminated(72): LC_TERMINAL=iTerm2 SHLVL=1 SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk _=/usr/bin/swift COLORTERM=truecolor HOME=/Users/admin LC_TERMINAL_VERSION=3.4.3 TERM=xterm-256color TERM_PROGRAM=iTerm.app LANG=en_AU.UTF-8 ITERM_PROFILE=Custom Terminal LOGNAME=admin __CF_USER_TEXT_ENCODING=0x1F5:0:15 XPC_FLAGS=0x0 COLORFGBG=7;0 CPATH=/usr/local/include TERM_PROGRAM_VERSION=3.4.3 ITERM_SESSION_ID=w0t0p0:B98AD1E5-A6DF-4DA4-B992-8268C6ED976F USER=admin TERM_SESSION_ID=w0t0p0:B98AD1E5-A6DF-4DA4-B992-8268C6ED976F PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.BhijhDcIOO/Listeners OLDPWD=/Users/admin LIBRARY_PATH=/usr/local/lib XPC_SERVICE_NAME=0 PWD=/Users/admin/ChangeMenuBarColor TMPDIR=/var/folders/rt/cxkhbxq11051rn6gdmwqtgmw0000gn/T/ SHELL=/bin/bash /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH

**Comment by igorkulman** [comment]
This probably means you do not have XCode installed or set.

**Comment by ArrowNemesis** [comment]
@igorkulman I do have XCode installed

**Comment by ArrowNemesis** [comment]
@igorkulman How do I set it up then?

**Comment by ArrowNemesis** [comment]
and btw I tried editing Package.swift and set it to 10.15 but same error. Pls help thank you.

**Comment by igorkulman** [comment]
Make sure `xcode-select -p` points to Xcode.

**Comment by ArrowNemesis** [comment]
ok I'll try that

**Comment by ArrowNemesis** [comment]
@igorkulman executing xcode-select -p gave me this output "/Library/Developer/CommandLineTools"

**Comment by ArrowNemesis** [comment]
I'm using zsh, should I switch to bash?

**Comment by igorkulman** [comment]
Open Xcoe

> 
> 
> @igorkulman executing xcode-select -p gave me this output "/Library/Developer/CommandLineTools"

This is the problem, Xcode is set just to Xcode tools not the full Xcode. Open Xcode, go to Preferences, Locations, set Command Line Tools to the Xcode installation.

**Comment by ArrowNemesis** [comment]
> Open Xcoe
> 
> > @igorkulman executing xcode-select -p gave me this output "/Library/Developer/CommandLineTools"
> 
> This is the problem, Xcode is set just to Xcode tools not the full Xcode. Open Xcode, go to Preferences, Locations, set Command Line Tools to the Xcode installation.

Ah right thank you so much, you're legend! Keep up the good work 💯 👍 :)

**Comment by ArrowNemesis** [comment]
@igorkulman I'm actually receiving an error this is what I get: 

./ChangeMenuBarColor SolidColor "#000000"
dyld: Library not loaded: /System/Library/Frameworks/Accessibility.framework/Versions/A/Accessibility
  Referenced from: /Users/admin/ChangeMenuBarColor/./ChangeMenuBarColor
  Reason: image not found
Abort trap: 6

please help, thank you

**Comment by igorkulman** [comment]
This is because the code uses Big Sur features.  You can make some.code changes to make it work with Catalina by removing the Accessibility framework and remove the AXColorName usages

**Comment by ArrowNemesis** [comment]
@igorkulman How do I do that?

**Comment by ArrowNemesis** [comment]
Sorry, I'm new to XCode

**Comment by ArrowNemesis** [comment]
I'm not too sure but is this how you do it. I opened up SolidColor.swift via XCode and now do I delete? "import Accessibility" and this      Log.debug("Generating \(AXNameFromColor(color.cgColor)) solid color image")
        guard let topImage = createSolidImage(color: color, width: screen.size.width, height: screen.menuBarHeight) else {
            return nil
        }

**Comment by igorkulman** [comment]
I have updated the project. Should be now buildable on Catalina.

**Comment by ArrowNemesis** [comment]
Ok Great I'll try it now

**Comment by ArrowNemesis** [comment]
@igorkulman Absolute genius! thank you now working and supported yay! 💯 👍 🥇 :)
