### ISSUE TITLE
Catalina MenuBar SolidColor not completely black 

### ISSUE THREAD

**Issue by ArrowNemesis** [igorkulman/ChangeMenuBarColor#43]
Using currently set macOS wallpaper file:///System/Library/Desktop%20Pictures/Solid%20Colors/Black.png
Generating sRGB IEC61966-2.1 colorspace 0 0 0 1 solid color image
 
When I execute ./ChangeMenuBarColor SolidColor "#000000", I'm not getting the hex color of "#000000" I'm getting "#000001"

**Comment by ArrowNemesis** [comment]
I don't mind it, but if it can be fix that would be great

**Comment by ArrowNemesis** [comment]
![Dark](https://user-images.githubusercontent.com/77384192/105632442-3a900b00-5ea7-11eb-974c-19685e7e1563.png)
I want it like this

**Comment by ArrowNemesis** [comment]
![image](https://user-images.githubusercontent.com/77384192/105632469-5a273380-5ea7-11eb-8252-fbe25796bccd.png)
here is my one

**Comment by igorkulman** [comment]
Catalina's menu bar works differently. You will never get the same results as on Big Sur

**Comment by ArrowNemesis** [comment]
> Catalina's menu bar works differently. You will never get the same results as on Big Sur

Oh ok, that's fine thanks anyways

**Comment by ArrowNemesis** [comment]
@igorkulman I'll install Big Sur once 11.2 has released since they will fix the bypass firewall issues etc.
