### ISSUE TITLE
error when is type "swift build -c release"

### ISSUE THREAD

**Issue by quentinfabrie** [igorkulman/ChangeMenuBarColor#45]
when i Say swift build -c release i get an strange error whitch i can't solve. here under is show the error.
error: terminated(72): LOGNAME=quentin USER=quentin SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk LIBRARY_PATH=/usr/local/lib XPC_SERVICE_NAME=0 HOME=/Users/quentin SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.tZ0VL2uV5u/Listeners _=/usr/bin/swift OLDPWD=/Users/quentin LaunchInstanceID=8004D82A-7047-42B8-A96C-E413B245A7D3 SHLVL=1 PWD=/Users/quentin/ChangeMenuBarColor SHELL=/bin/zsh CPATH=/usr/local/include SECURITYSESSIONID=18770 TERM_PROGRAM_VERSION=440 TMPDIR=/var/folders/bz/bxfswftj3597r09r673yt05m0000gq/T/ __CFBundleIdentifier=com.apple.Terminal PATH=/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands XPC_FLAGS=0x0 TERM_SESSION_ID=8AAA91F2-6F41-424E-BDB2-067C62512057 __CF_USER_TEXT_ENCODING=0x1F7:0x0:0x5 TERM=xterm-256color TERM_PROGRAM=Apple_Terminal LANG=nl_NL.UTF-8 /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH

Maybee someone know what't wrong

**Comment by igorkulman** [comment]
Duplicate ot #40

**Comment by quentinfabrie** [comment]
thx i didn't saw that
