### ISSUE TITLE
Suggestion: Transparency Option to Menu Bar Color

### ISSUE THREAD

**Issue by takuhii** [igorkulman/ChangeMenuBarColor#46]
Hi,
Would it be possible to apply a transparency option to the app? I was think that if you applied an ALPHA value to the color specified (maybe as an additional flag)?

`./ChangeMenuBarColor TransparentColor "desired_hex_color" "4"`

This could maybe work in 20% increments like this; 1-20% - 2-40% - 3-60% - 4-80% - 5-100%

If you are using something like ImageMagick in the background, then this can be done like this;
https://imagemagick.org/script/compose.php

Sorry to abuse the issues function in this way...

Cheers
Darren

**Comment by igorkulman** [comment]
I think the best way would be supporting the ARGB notation, so say `#80FFFF00` as 50% transparent yellow.

**Comment by igorkulman** [comment]
You can use `./ChangeMenuBarColor SolidColor "#80FFFF00"` now with the latest code.

**Comment by takuhii** [comment]
LEGEND ;)
