### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aholub** [igorkulman/ChangeMenuBarColor#52]
Fails catastrophically with a seg fault (the error message is "Segmentation fault: 11") under MacOS 11.2, executed with:

> ./ChangeMenuBarColor SolidColor #CCCCCC

**Comment by igorkulman** [comment]
Please post the full output. Also have you built it yourself or used the binary from Releases?

**Comment by aholub** [comment]
Hi Igor:

Not much output to report. I used the prebuilt binary. I can build it
locally, though. I'll try that.

[image: Screen Shot 2021-04-28 at 11.15.40 AM.png]

-Allen

*_______________________**__________________*
Allen Holub  ◇  @allenholub   ◇  +1 (510) 859-3620
http://holub.com  ◇  http://linkedin.com/in/allenholub

**Comment by igorkulman** [comment]
Any luck with building from source?

**Comment by aholub** [comment]
Hi Igor. Just tried it. No luck. It compiled w/o problems.

-Allen

[image: Screen Shot 2021-04-29 at 4.16.03 PM.png]

*_______________________**__________________*
Allen Holub  ◇  @allenholub   ◇  +1 (510) 859-3620
http://holub.com  ◇  http://linkedin.com/in/allenholub

**Comment by aholub** [comment]
Hi Igor. I just installed today's Xcode update and recompiled, and it's now
working fine. Mysterious, but it does now work.

-Allen
*_______________________**__________________*
Allen Holub  ◇  @allenholub   ◇  +1 (510) 859-3620
http://holub.com  ◇  http://linkedin.com/in/allenholub
