### ISSUE TITLE
Something that should be noted in the README

### ISSUE THREAD

**Issue by TheMartian32** [igorkulman/ChangeMenuBarColor#53]
Hi,

So after a very frustrating 30 minutes of errors telling me it doesn't work, I tried turning off the "hide menu bar automatically in system preferences" and everything worked. So, I feel this should be noted in the README to prevent people from having to spend so much time on this. Thanks!

**Comment by igorkulman** [comment]
Thanks for the feedback. I did not expect anyone to use this with autohidding menu bar as to me it does not make much sense, you would end up with a colored rectangle on top that looks strange. But I will update the Readme just in case.

**Comment by TheMartian32** [comment]
Thanks! Reading it back now it doesn't make much sense, but great job on the project! Really enjoying my new menu bar.
