### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by skitzcod4** [igorkulman/ChangeMenuBarColor#57]
Hello,

I had some trouble setting up the project (werent able to build the swift package) but now I did some changes to my Xcode and it compiled successfully. But the only problem I have (same with the prebuilt version) is that he always tells me that he cant find the ChangeMenuBarColor Command.
![image](https://user-images.githubusercontent.com/36051277/124868839-aaf79800-dfc0-11eb-9708-fd80ae92f76d.png)
Any solutions?

// Edit:
MacBook Pro M1 with latest Swift and Xcode versions installed

**Comment by igorkulman** [comment]
You need to follow the readme exactly, so not `ChangeMenuBarColor` but `./ChangeMenuBarColor`
