### ISSUE TITLE
[Feature Request] Monterey support?

### ISSUE THREAD

**Issue by seanbperiod** [igorkulman/ChangeMenuBarColor#58]
Just tried running this on 12.1 but got errors. Hoping this can be updated to add support. Thanks!

**Comment by Red-Pi** [comment]
It works fine for me on Mac OS 12.0.1 on an M1 MacBook Air.
Build from source and ran the tool.

**Comment by igorkulman** [comment]
@seanbperiod people are reporting that it works just fine on Monterey. Maybe try opening Xcode first so it install all the command line tools etc. Or open the folder in Xcode and try building it from there.

**Comment by igorkulman** [comment]
I am on Monetery now, everything works fine, closing.
