### ISSUE TITLE
mint run igorkulman/ChangeMenuBarColor failed

### ISSUE THREAD

**Issue by zakirsajib** [igorkulman/ChangeMenuBarColor#60]
Zakirs-MacBook-Pro:~ zakir$ mint run igorkulman/ChangeMenuBarColor
🌱 Finding latest version of ChangeMenuBarColor
🌱 Cloning ChangeMenuBarColor v1.0.1
🌱 Resolving package
error: terminated(72): /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve ChangeMenuBarColor v1.0.1 with SPM
Zakirs-MacBook-Pro:~ zakir$

**Comment by igorkulman** [comment]
You need to have Xcode installed

**Comment by zakirsajib** [comment]
> You need to have Xcode installed and opened at least once. I will add it to README.

but xcode is 12GB, is there any other way to do that ?

**Comment by igorkulman** [comment]
You can try downloading the latest release binary but it is not guaranteed to work because of signing https://github.com/igorkulman/ChangeMenuBarColor/releases

**Comment by zakirsajib** [comment]
downloaded it and then run following:
Zakirs-MacBook-Pro:~ zakir$ mint run /Volumes/My\ Drive2/Safari\ Downloads/ChangeMenuBarColor SolidColor "#FFFFFF"
🌱 Finding latest version of ChangeMenuBarColor
Username for 'https://github.com': zakirsajib


but stuck there. nothing happening.

**Comment by igorkulman** [comment]
Just `/Volumes/My\ Drive2/Safari\ Downloads/ChangeMenuBarColor SolidColor "#FFFFFF"`

**Comment by zakirsajib** [comment]
works. Cheers.

**Comment by ibehnam** [comment]
Everytime it creates the new wallpapes in `/Users/<user-name>Library/Application Support/ChangeMenuBarColor/`. Is there a way to change that?

**Comment by igorkulman** [comment]
@ibehnam the path is not configurable and the app does not "clean up" old wallpapers at the moment.
