### ISSUE TITLE
'mint run igorkulman/ChangeMenuBarColor' installation failed

### ISSUE THREAD

**Issue by peanut0713** [igorkulman/ChangeMenuBarColor#62]
Hello, now there is a little problem here when executing the second part of install mint, Hello, now there is a little problem here when executing the second part of install mint, the error message is displayed as follows:

error: terminated(72): /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve ChangeMenuBarColor v1.0.1 with SPM

OS: macOS Big Sur (M1)

![1647938408089](https://user-images.githubusercontent.com/38377645/159440926-4955e8e2-b69b-4f22-9e89-0fd4bc88e238.jpg)

**Comment by igorkulman** [comment]
You need Xcode installed as written in Readme.

**Comment by igorkulman** [comment]
You need to run it at least once

**Comment by peanut0713** [comment]
thanks, it's resolved
