### ISSUE TITLE
Reset/Goback verb

### ISSUE THREAD

**Issue by AjaxLeVallee** [igorkulman/ChangeMenuBarColor#65]
With the Dynamic wallpapers etc, it would be nice if this could have a reset function where we can go back to the default of whatever the system was first set to.

**Comment by igorkulman** [comment]
That would require the tool to somehow remember the previous setting, adding unnecessary complexity. This tool is intended just to one off set a wallpaper with a menu bar sized colored rectangle, nothing more.
