### ISSUE TITLE
Feature request: If no path is given use current wallpaper

### ISSUE THREAD

**Issue by Rastafabisch** [igorkulman/ChangeMenuBarColor#7]
If no path is given it would be great, if your tool would default to the current wallpaper path.

[This could be obtained with a small using sqlite](https://apple.stackexchange.com/questions/20136/where-does-os-x-store-your-current-desktop-picture/341158#341158):
`sqlite3 -readonly ~/Library/Application\ Support/Dock/desktoppicture.db \
    'SELECT * FROM data ORDER BY rowID DESC LIMIT 1;'`

Additionally the new file could also be written to this path, so it would be automatically applied.

**Comment by Rastafabisch** [comment]
Wow, that was fast! Kudos.

**Comment by danilokleber** [comment]
I guess this is not working anymore in Sonoma? It always prints `Using currently set macOS wallpaper file:///System/Library/CoreServices/DefaultDesktop.heic`, but my defined wallpaper is not that.
