### ISSUE TITLE
In MacOS Ventura not working

### ISSUE THREAD

**Issue by ObscurusGrassator** [igorkulman/ChangeMenuBarColor#72]
Setuped colors are a bit transparent in MacOS Ventura.
When I disable in system settings bars transparent, ChangeMenuBarColor is totally not working.

**Comment by ingozoell** [comment]
Any update planed for macOS 13 Ventura? Thanks, Ingo

**Comment by igorkulman** [comment]
That is a limitation of the approach, you need to keep the menu bar transparent so the generated color is visible through it.

**Comment by ingozoell** [comment]
I unterstand, thanks for info.
